### ISSUE TITLE
JEI shows "Scraping" possibility for all items

### ISSUE THREAD

**Issue by Regulith** [gigaherz/Survivalist#10]
Looking at the uses for an item in JEI while using the Just Enough Resources add-on, it appears that every single item in the game can receive the Scraping enchantment, not just the intended tools and armor. They can't actually be enchanted, but the UI shows that they can receive that specific enchantment nonetheless.

Basically it shows [this screen](http://i.imgur.com/1fsDcHJ.png) for everything from Stone to Rail to Redstone and everything beyond, including mod items.

Unsure if this is a Survivalist or JEI/JER issue, but wanted to bring it up just in case.

**Comment by gigaherz** [comment]
I do allow the enchantment on "anything that is enchantable". See: https://github.com/gigaherz/Survivalist/blob/master/src/main/java/gigaherz/survivalist/scraping/EnchantmentScraping.java#L13

However, I don't think there is any way to specify "only tools, armor and weapons"... It may simply be a design defect, and not really a bug by any of us.

**Comment by gigaherz** [comment]
I'm really not seeing any way to solve this. I'll talk with the JER people to see if they have any idea about it.

**Comment by gigaherz** [comment]
Turns out the solution was simply to use `EnumEnchantmentType.BREAKABLE` rather than `EnumEnchantmentType.ALL`. I mistook "ALL" to be "All tools, weapons, and armor" rather than its more literal meaning of "any item in the game, including blocks in their item form".

**Comment by gigaherz** [comment]
v1.6.5 is up and fixes this issue!
