### ISSUE TITLE
Mod Doesn't work with altered level.dat

### ISSUE THREAD

**Issue by teagan75** [gigaherz/Survivalist#104]
So, here is a strange issue I haven't had with any of the other mods in my pack. I used the Buffet generator for Caves. Then I altered the level.dat to have all vanilla biomes instead of just one. This is what I did:

level.dat
 - Data
    - generatorOptions
       - biome_source
         - options
            - biomes
               - minecraft:checkered
        - type: vanilla_layered

Like I said, your mod is the only one causing me issues.

**Comment by gigaherz** [comment]
Uhm, what *is* the issue, though? you only said it happens in that situation, but not *what* happens in that situation?

**Comment by teagan75** [comment]
Sorry, when I try to mine ore and stone it doesn't drop your items. It drops vanilla items. If I create a "normal" world it drops your modded items

**Comment by gigaherz** [comment]
Huh, that is strange. What version of mc/forge? 1.16.1? I'll have to check but it strongly sounds like you stumbled on a forge bug.

**Comment by teagan75** [comment]
Mc version: 1.15.2
Forge: 31.2.31

I took your mod out and tried to get iron ore to drop a nugget with no luck. It works in other worlds just not the checkered. So I guess it’s probably a Minecraft bug

**Comment by teagan75** [comment]
NOPE! I am the idiot lol. Thanks for your patience. It is what I get from trying something "secret" :P I put checkerboard in the type not biome 🤦
