### ISSUE TITLE
Error during Setup, Minecraft 1.16.1, Forge 32.0.107

### ISSUE THREAD

**Issue by ZylaFae** [gigaherz/Survivalist#105]
While using Forge 32.0.107 for Minecraft 1.16.1, minecraft fails with the error message "Survivalist (survivalist) encountered an error during the sided_setup event phase" "Can not register model loaders after models have started loading. Please use [...]"

This appears to be due to your movement of the ModelRegistryEvent in Forge 32.0.107, as it works fine in Forge 32.0.106

As this is an error in differences between versions of Forge, would it be possible to add a line to the ReadMe or wiki saying which version of Forge the mod was most recently tested with?

**Comment by gigaherz** [comment]
Yep, I have a fixed version, I just didn't publish it to curseforge yet.

**Comment by gigaherz** [comment]
v3.2.2 should fix the issue.
