### ISSUE TITLE
1.16.3, Forge 34.1.5 - Crashing in singleplayer world

### ISSUE THREAD

**Issue by xXJamieXx** [gigaherz/Survivalist#106]
Survivalist version 3.2.3
Minecraft 1.16.3
Forge 34.1.5

Game is crashing whilst playing fairly often (crashed twice in about 5 minutes). Not sure what the cause is as it just seems to happen with no real explanation or during any particular thing I'm doing, not really getting chance to do much as its happening not long after world load. 

[crash log](https://pastebin.com/AYNm3pcD)

Thanks :)

**Comment by gigaherz** [comment]
It seems to be an issue in the "slime merge" feature. I'll take a look as soon as I can. Meanwhile, you can try to disable the feature from the server config file, in the save folder.

**Comment by xXJamieXx** [comment]
Perfect thank you. Disabling does indeed prevent the crashes :)
