### ISSUE TITLE
I can craft 4 oak planks from a log [1.16.3]

### ISSUE THREAD

**Issue by vinnyg0621** [gigaherz/Survivalist#107]
![2020-10-23_14 27 35](https://user-images.githubusercontent.com/57818441/97055860-7d56e580-153c-11eb-88a1-74d7cb6085c5.png)

**Comment by gigaherz** [comment]
There's a bug in the config. The value `ReplacePlanksRecipes` is reversed, and needs to be changed to false for the normal behaviour to work. I will try to fix as soon as I can.

**Comment by vinnyg0621** [comment]
okay, got it
