### ISSUE TITLE
Chopping block not using axe durability

### ISSUE THREAD

**Issue by Silvrus** [gigaherz/Survivalist#11]
Hey bud! Having a lot of fun with this, but I just noticed the axe isn't taking damage when used on the chopping block. Not sure if it's a concern for you, but I thought I'd let ya know.

**Comment by gigaherz** [comment]
Oh! I forgot about that. Nice catch. I'll try to add that at some point over the week.

**Comment by gigaherz** [comment]
v1.6.5 is up and fixes this issue!
