### ISSUE TITLE
Survivalist Recipe Clash

### ISSUE THREAD

**Issue by KritantaM** [gigaherz/Survivalist#111]
The crude spade and flint knife both uses 1 stick and 1 flint. Whenever I try to craft the flint knife I receive the crude spade instead. I also can't use the regular crafting table making it impossible to do anything.

**Comment by gigaherz** [comment]
Survivalist doens't have a flint knife, so I presume you mean the flint knife from another mod. I can't possibly change my recipes every time someone happens to find a mod that clashes with mine, so I consider this to be not my fault.
If you want to play with two mods that have clashing recipes, you'll want to either customize the recipes yourself (eg, by using a datapack), or use a mod that lets you pick which output you want, in case of conflict.
