### ISSUE TITLE
not enought information for using this mod

### ISSUE THREAD

**Issue by sbuisson** [gigaherz/Survivalist#12]
you should add to your wiki how to do iron lingo, jerky, coblestone etc. We don't have enought informations to use your mod.

**Comment by gigaherz** [comment]
Hopefully, this is enough: https://github.com/gigaherz/Survivalist/wiki

**Comment by sbuisson** [comment]
Thanks , but you should add the recipes

**Comment by gigaherz** [comment]
You can see them in JEI?

**Comment by gigaherz** [comment]
Also, there aren't any complicated recipes. Maybe the least visual is the chainmail one, so I'll add that one, but I don't think anything else is needed.
