### ISSUE TITLE
Crash related to explosions

### ISSUE THREAD

**Issue by Regulith** [gigaherz/Survivalist#13]
A Creeper exploded near me on the surface of the overworld and it crashed the game, then prevented me from loading the world until I disabled Survivalist. [Crash log is here.](http://pastebin.com/Qtgz0ZYq)

I don't really have a way of knowing for sure, but I'm convinced the Creeper had special attributes from Infernal Mobs, since the crash log claims there was a fireball involved and I found the ground covered in flames after I removed Survivalist and loaded into the world. There aren't any other sources I can think of that would've caused the fire. I think the crash has something to do with the game failing to generate the rock items when some stone exploded? Most likely a very niche problem to have, but still. I have a backup of the moment the game crashed, so I can test things if you'd like.

**Comment by gigaherz** [comment]
Uhm.... oops. I'll fix later after work.

**Comment by gigaherz** [comment]
Upon closer inspection, the issue isn't really mine, so much as another mod returning an ImmutableList from their getDrops. I have written a workaround to avoid the crash, but I still consider it not my fault.

**Comment by gigaherz** [comment]
v1.6.6 is up, curseforge soon.

**Comment by Regulith** [comment]
Ah, I see, I just hastily assumed it was related to Survivalist because of the circumstances. Thanks for looking at it anyway.

**Comment by gigaherz** [comment]
Well the issue IS related -- in that I didn't consider the possibility of other mods doing something like that. ;P
