### ISSUE TITLE
Copping block suggestion

### ISSUE THREAD

**Issue by MechWarrior99** [gigaherz/Survivalist#15]
While playing with the chopping block I have noticed that it feels rather unnatural to left click it. I feel that right clicking it with the axe feels much more normal, plus that way it could be used in Creative. 

Just a suggestions I thought I would mention.

**Comment by gigaherz** [comment]
I prefer to keep it as it is. What I'd like to find, is a way to override the breaking, so that you can hold the mouse button down rather than click multiple times.

**Comment by MechWarrior99** [comment]
Okay, that would be nice if we didn't have to worry about breaking it.
