### ISSUE TITLE
CraftTweaker chopping block feature request

### ISSUE THREAD

**Issue by MechWarrior99** [gigaherz/Survivalist#16]
It would be really nice if you could specify the number/rough number of hits it takes when using the chopping block.

**Comment by gigaherz** [comment]
Hmm I guess I could split the speed multiplier away from the loot multiplier...

**Comment by gigaherz** [comment]
v1.8.0 is out and among other things, expands the CraftTweaker support to include a 4th parameter, for the hit count modifier (1.0 is default, and a different number would adjust how much progress each hit makes, so that 0.5 would make it take twice as long as usual).
