### ISSUE TITLE
Hatchet collides with other item based mods!

### ISSUE THREAD

**Issue by Schmorgus** [gigaherz/Survivalist#18]
No issues actually running it, but the Hatchet recipe isn't working anymore with tcontruct!
Would be awesome if this tiny problem could be fixed :)

**Comment by gigaherz** [comment]
Does it just not work at all? Or does it conflict with another recipe that has the same inputs?

**Comment by Schmorgus** [comment]
The mod in itself works, but when i load it with Tinkers Construct, the Hatchet recipe can't be used. Can't see recipe with 'Just Enough Items', only the Hatchet in the list but nothing happens when i click it for recipe preview.

**Comment by Schmorgus** [comment]
I can't find any recipe in Tinkers that would resemble your Hatchet. And i'm no coder so i don't know whats wrong :P Nothing about it in any config though!

**Comment by gigaherz** [comment]
Weird. I'll check it out as soon as I get home.

**Comment by gigaherz** [comment]
I have just loaded TiCon on my development environment, and it works just fine. Do you have any other mods installed?

**Comment by Schmorgus** [comment]
Lets see, i have a Mod Pack with everything, lastest aditions was TiCon and Pam's Harvest.
I need to go through the list and think, but thought TiCon was the reason since i added that one last xD

**Comment by Schmorgus** [comment]
I also added Craft++

**Comment by Schmorgus** [comment]
Just remembered that "Actually Additions" was added aswell :P Sorry for being such a pain!

**Comment by Schmorgus** [comment]
I've been going through the mods, adding and removing them one by one.
When i disable Tinker's Construct (and Mantle since dependable) i can craft the Hatchet :P
So it have to do with either Tinker's, or Mantle.

**Comment by Schmorgus** [comment]
Problem is, i can see the Hatchet item in the JEI-list to the right,
but i can't click it to see the recipe, nor craft it (nothing shows up when crafting).

**Comment by gigaherz** [comment]
Weird! I'll investigate further...

**Comment by Schmorgus** [comment]
On a sidenote, i love your mod! I was SO tired of all those mainstream-mega-mods :P Your mod makes everything how it should've been in vanilla :)

**Comment by gigaherz** [comment]
Thanks :3

**Comment by gigaherz** [comment]
Can't seem to reproduce >_<

My best suggestion right now is that you add CraftTweaker to the mix, and "add back" the shapeless recipe for the hatchet.

**Comment by Schmorgus** [comment]
I tried that, didn't work :( But Tinker's remove basic vanilla items, might it be that your hatchet is "classed" as a basic item?

**Comment by gigaherz** [comment]
Not so far as I know... I do add it to the "tools" tab on the creative menu, rather than my own, but as I said, it works just fine on both my local testing setup, and my local development setup...

Can you try to remove all the mods EXCEPT TiCon(+mantle) and mine? If it still fails, I'd like to take a look at your settings, and I'd need more details about the exact versions of forge and the mods you use.

**Comment by Schmorgus** [comment]
Are you using Curse? I have the profile setup there :P

**Comment by gigaherz** [comment]
Sure.

**Comment by Schmorgus** [comment]
My profile name is Infektard
