### ISSUE TITLE
Chopping block usage hunger cost

### ISSUE THREAD

**Issue by charlie-e09ae35d** [gigaherz/Survivalist#19]
Since player using Chopping block is using an axe in a similar fashon like when harvesting a block, would you consider adding saturation/hunger cost to it (like in case of normal block breaking)?
If the hunger cost will not be configurable would it be possible to make it compatible with custom values possible thanks to Exhaustion Tweaks mod?
[Hunger - Exhaustion level increase - Official Minecraft Wiki](http://minecraft.gamepedia.com/Hunger#Exhaustion_level_increase)
[Exhaustion Tweaks - Minecraft CurseForge](https://minecraft.curseforge.com/projects/exhaustion-tweaks)
[Exhaustion Tweaks - GitHub](https://github.com/xkyouchoux/Exhaustion-Tweaks)

**Comment by gigaherz** [comment]
Hey, I know it took a while to get around to doing this, but next release (later today) will have a (configurable) exhaustion cost on chopping.

**Comment by charlie-e09ae35d** [comment]
Great to know, thanks for your continuous work and support for this neat mod.
