### ISSUE TITLE
World Loading Errors

### ISSUE THREAD

**Issue by Darkosto** [gigaherz/Survivalist#20]
Heya Gigaherz! Thanks again for this mod, I'm enjoying the heck out of it for my new pack!! Thank you for adding the field for custom hatchets :D 

Is it possible to check out these world loading errors? http://pastebin.com/GhAmvsLu

This happens when starting/loading up the world.

Forge: 2124
Survivalist version: 1.7.10
MC: 1.10.2

**Comment by gigaherz** [comment]
Version of JEI and minetweaker?

**Comment by Darkosto** [comment]
JEI: 3.13.3.372
Minetweaker:  3.0.14

**Comment by Darkosto** [comment]
Let me know if you'd like me to do some testing for you before you push any releases :)

**Comment by gigaherz** [comment]
No need, it's [already up](https://github.com/gigaherz/Survivalist/releases/tag/v1.7.2-1.10.2), and waiting for review in curseforge. Hopefully everything works. Reopen if there's some problem. ;P

**Comment by gigaherz** [comment]
Oops. I just got exploded by a creeper doing some further testing, and it blew the server up. XD

**Comment by Darkosto** [comment]
LOL! Thanks again for the help :)

**Comment by gigaherz** [comment]
1.7.3 is up, btw.
