### ISSUE TITLE
Chopping block BROKEN!

### ISSUE THREAD

**Issue by Fishy3317** [gigaherz/Survivalist#21]
I click the the wood on the chopping block, but when i do, I get nothing back. PLZ fix this. (or tell me whats wrong).
-Fishy

**Comment by gigaherz** [comment]
Version of Survivalist? Version of Forge?

**Comment by gigaherz** [comment]
Are you by any chance leaving the button pressed? The chopping block requires you to click multiple times.

**Comment by Fishy3317** [comment]
Sorry I couldn't respond sooner. I restarted my game a couple of times and
it was fixed. -Fishy

On 27 Nov 2016 11:40 PM, "David Quintana" <notifications@github.com> wrote:
>
> Are you by any chance leaving the button pressed? The chopping block
requires you to click multiple times.
