### ISSUE TITLE
Chopping block gives no items.

### ISSUE THREAD

**Issue by AndaleTheGreat** [gigaherz/Survivalist#22]
Any type of log placed gives no planks. Recipe for planks does not show in JEI. (I am just clicking, not breaking the chopping black.

**Comment by gigaherz** [comment]
What version of Survivalist? and forge? 

Do you have other mods installed? There is the possibility that some other mod is removing the planks recipes before Survivalist has a chance to import them into the chopping block.

**Comment by AndaleTheGreat** [comment]
Sorry, meant to copy this line into the message and apparently hit submit without checking.
List of installed mods with versions: http://i.imgur.com/kcETHbX.png
Forge 13.19.0.2178 (1.11)

**Comment by gigaherz** [comment]
Hey, I finally got around to checking this issue, but I can't figure out which mod "harvest-1.11-1.20-12.jar" belongs to.

**Comment by gigaherz** [comment]
Nope, I still can't reproduce.

**Comment by AndaleTheGreat** [comment]
Title is not quite right I guess. It does give items, just not when I expected.

Problem was I had this installed on a new world (with bonus chest) and only had the wood axe which does not give anything. I assumed it was a bug because the log still disappears but you do not get it back. Same with anything other than stone axe or better.
So, yeah. unless you count not getting my log back then I would consider it closed. Tho I gotta wonder how you start a new world with this mod even installed.

**Comment by gigaherz** [comment]
Make a hatchet. You need 1 stick, 1 flint, and 1 string. :P

**Comment by AndaleTheGreat** [comment]
Ah, ok, I missed that. Maybe I read it when I first grabbed it but since then I've forgotten.
Alright, I got another one I'm gonna post for ya with a video too.
