### ISSUE TITLE
Chopping Block

### ISSUE THREAD

**Issue by DarkEclipseFate** [gigaherz/Survivalist#24]
Chopping block will not give me wooden planks

**Comment by gigaherz** [comment]
Are you using it right? you have to click multiple times and not hold the button down when using it.

If so, do you have any other mods that modify planks recipes?

**Comment by DarkEclipseFate** [comment]
Not that modify them
These are the major mods I have
Survivalist
Tough As Nails
Hardcore Survival
Iberia
Biomes O'Plenty
Deadly Monsters

**Comment by Inferno5** [comment]
you cant make planks with your hands. you need a crude hatchet instead.

**Comment by gigaherz** [comment]
Ah, yes. I forgot to mention that!

**Comment by gigaherz** [comment]
If you click with your hands, you have, by default, a 60% chance to lose the item, and a 40% chance to get it back. For sticks, the output numbers are doubled: so you have an 80% chance of getting 1 stick, and a 20% chance of getting none.
