### ISSUE TITLE
Chopping block & Better With Mods

### ISSUE THREAD

**Issue by Schwantastic** [gigaherz/Survivalist#26]
Better With Mods update that added hardcore stumping now makes logs unusable with the chopping block. I ran a test and disabled the mod in the curse client which made the logs usable again.

**Comment by gigaherz** [comment]
Hey sorry for taking a while to answer. I can't seem to be able to run BWM in my develoipment environment, so I have no idea if there's any way to work around the issue. Please note that my mod is highly configurable and you may be able to work around the issue by turning some features off.
