### ISSUE TITLE
Feature request - Configure drying rack times

### ISSUE THREAD

**Issue by Gxinva** [gigaherz/Survivalist#27]
If possible could we have an option in the config to change drying rack times? i want to triple how long leather takes to tan, so as to add a tiny bit more realism and make having multiple stations worth it. same thing with dried meat. and such

**Comment by gigaherz** [comment]
Sure!

**Comment by Gxinva** [comment]
any idea on the time frame for the next update on the mod? I'm quite looking forward to making a personal survival/adventure/roleplay modpack with this and some other stuff like the roguelike dungeons mod and levelup

**Comment by gigaherz** [comment]
I have a very limited spare time these days, but I plan on dedicating some time to this mod, over the weekend. A new release may happen any time between later today (Friday), and Sunday -- if all goes well.

**Comment by gigaherz** [comment]
Hey, I have been looking at this, and I already have the ability to customize the times -- through CraftTweaker. Making this available in the config would be rather complex, and not any easier than setting up a crafttweaker script.

If you wanted to do this in 1.11, then I'm sorry, but I probably won't be doing this right now.

**Comment by Darkosto** [comment]
I wouldn't mind the CT integration, personally. That's something I would use a lot of :)

**Comment by gigaherz** [comment]
There's no default recipe to make leather from rotten flesh, it makes jerky.

**Comment by Darkosto** [comment]
Yeah, I just discovered that. That's definitely something CT would come in handy for :P 

Thank you again for the response.

**Comment by gigaherz** [comment]
As I said, CT support is available -- the only reason it doesn't work in 1.11 is because there is no CT released for 1.11. ;P

**Comment by Darkosto** [comment]
Hold on! Let me drink a bunch more coffee so I can wake up and read a bit better!

I'll dig up the syntax and work on some custom stuff. Thank you again!

**Comment by gigaherz** [comment]
Syntax is:

```
gigaherz.survivalist.Dryable.addRecipe(<minecraft:fish>,<survivalist:jerky>,500);
gigaherz.survivalist.Choppable.addRecipe(<minecraft:bone>,<minecraft:dye:15>,1);

```

The 500 is the number of ticks (20 per second). The "1" in chopping recipes is the output conversion rate multiplier.

**Comment by gigaherz** [comment]
Actually, I may be lying, I can't find the code anymore. I may have removed it from 1.10 at some point and forgot to add it back?

**Comment by Darkosto** [comment]
Yup, that was it. Thank you :)

**Comment by gigaherz** [comment]
v1.8.0 is out. Closing this since I won't be adding the configurable recipes in the mod code (for now) -- go poke the CraftTweaker people to make a 1.11 release instead. ;P
