### ISSUE TITLE
Chopping block CTD

### ISSUE THREAD

**Issue by Silvrus** [gigaherz/Survivalist#3]
Using the chopping block to create planks with your hand causes CTD. Tested with just Survivalist to rule out mod compatibility issues.

http://pastebin.com/3X0Z19ZQ

**Comment by gigaherz** [comment]
/me facepalms

I was so worried about it crashing with different tools and such, that I forgot to test for empty hand!

**Comment by gigaherz** [comment]
v1.5.1 is up here on github, curseforge incoming.

**Comment by Silvrus** [comment]
It's all good man, happens to everyone. I'll test out that version and let ya know, and thanks for the quick repsonse!

**Comment by Silvrus** [comment]
Well, good news is it doesn't CTD anymore. Bad news is you can't seem to get planks using your hand, lol

**Comment by gigaherz** [comment]
Yeah that's by design. XD

**Comment by Silvrus** [comment]
So.... how do you make the crafting table to make the axe to use with the chopping block? :p

**Comment by Silvrus** [comment]
Another thing that I noticed, BoP logs are still converting to planks. If that's not an easy fix, no worries, I can look into removing the recipes or something.

**Comment by gigaherz** [comment]
Oh, sh... I forgot about that! Hmm what would you think works best, that I replace the crafting table recipe, or that I allow using the hand to chop (with < 100% chance to get a result)?

I identify logs-to-planks recipes by checking the shaped recipes that have an output with ore dictionary name "plankWood" and a single input with ore dictionary name "logWood". I'll put BoP on the list of things to check, to see what sort of recipe they are using. If it's just shaped vs shapeless, it will be easy, but if it's something more abstract, then I'm not sure I want to start adding mod-specific hacks.

**Comment by Silvrus** [comment]
I would say using the hand to chop, with <100% and giving max of 1 plank would be in the best spirit of the mod. And I completely understand about mod specific things, I believe in Infinity Evolved Expert Mode they simply removed the recipe for BoP planks. No the cleanest solution but it does work.

**Comment by gigaherz** [comment]
v1.5.2 is up, curseforge incoming

**Comment by Silvrus** [comment]
Perfect, works beautifully! Thanks a lot man, you rock. So anything else on the horizon?

**Comment by gigaherz** [comment]
I'm quite busy these days, and have 5 mods in progress, so I don't foresee any new features any time soon. I had spent months trying to get an idea for how to allow planks-to-sticks, so when I got the idea for the chopping block I really had to do it. However, who knows, maybe I get some random idea and decide to implement it. And suggestions are always welcome.

**Comment by Silvrus** [comment]
Good deal bud, really appreciate the help. Keep up the good work!
