### ISSUE TITLE
[Enhancement] Any mod log chopping block

### ISSUE THREAD

**Issue by WolfieWaffle** [gigaherz/Survivalist#31]
I think it would be cool to add support for any log block for the chopping block, I know it is possible based on Agricraft, which dynamically adds certain blocks with any wood texture and recipe. But I think it requires NBT, which may not be something you want.

**Comment by gigaherz** [comment]
Adding alterantives for the *vanilla* blocks has been in my mind for a long time. Mod logs however, that'd be more annoying. It is true that I would indeed need to attach extra data to the block and the item version of the block, but NBT isn't an issue, and for the block, it already has a TileEntity so storing one more value isn't the issue. 

The problem with mod logs would be figuring out which textures to use, and generating the "broken" textures for them. It's not easy by itself, and it becomes impossible if the player has a mod or resourcepack that changes the model of the logs.

**Comment by WolfieWaffle** [comment]
Ah, I forgot about the models. I think the whole JSON model thing hurt modding more than it helped, personally, but maybe you could just use the default textures that ship with a mod. I don't know how that works though, so maybe not. For the crack texture I assume you could just use an overlay like vanilla block breaking has.

**Comment by gigaherz** [comment]
Sneak peek to v2.0 which will release for 1.12 soon :P

![2017-08-06_03 15 28](https://user-images.githubusercontent.com/685851/28999803-dcdc37f6-7a55-11e7-81bc-4ad43c48f93b.png)

(Only vanilla logs, I don't think I'll be doing mod logs any time soon)
