### ISSUE TITLE
Compatibility with Railcraft

### ISSUE THREAD

**Issue by liach** [gigaherz/Survivalist#33]
Moved from CovertJaguar/Railcraft#1085, it seems such compatibility is handled on your side.
The ore dictionary entries can be found here:
https://github.com/CovertJaguar/Railcraft/blob/54bc41a3ca02a9e325945d7f8202960001f75673/src/main/java/mods/railcraft/common/blocks/ore/BlockOre.java#L102-L107

**Comment by gigaherz** [comment]
Thanks. Will look into it.

**Comment by liach** [comment]
Related code: https://github.com/gigaherz/Survivalist/blob/master/src/main/java/gigaherz/survivalist/rocks/RocksEventHandling.java#L77-L107

**Comment by gigaherz** [comment]
How much do those "poor ores" smelt for, normally?

**Comment by liach** [comment]
2 nuggets. Gregtech can make it into 1/4 ore dust

**Comment by gigaherz** [comment]
Survivalist v2.0 (for 1.12.1) will include support for poor ore drop replacement. The rate will be 1 rock + 50% chance of the second drop. Fortune will affect these drops (all the rock drops, not just poor ores), meaning getting more than 2 will be possible, with luck.

I may or may not backport 2.0 to older versions in the future. I haven't decided yet.
