### ISSUE TITLE
[1.10.2] Crash with TiCon

### ISSUE THREAD

**Issue by Silvrus** [gigaherz/Survivalist#36]
Hey dude, long time! Putting together a new pack, ran into a crash using a TiCon hatchet. Here ya go: https://gist.github.com/Silvrus/4adeb5082011a9fe6f9bf7e82cde8032

**Comment by gigaherz** [comment]
Hmm this crash has been reported before, in #25. It's something that should be fixed in TiCon, since I can't fix it from my end. Basically: they are not properly null-checking a parameter that is @Nullable.

**Comment by gigaherz** [comment]
I don't know if the other reporter told the TiCon people, could you open a report with them?

**Comment by Silvrus** [comment]
Sure thing, I'll check out their github and post it up if it's not there.

**Comment by Silvrus** [comment]
So Boni figured out what was happening and is fixing it. Thanks again bud!
