### ISSUE TITLE
[1.11.2-1.8.4] log disappears, no planks or sticks received

### ISSUE THREAD

**Issue by kreezxil** [gigaherz/Survivalist#37]
I was getting ready to go through my mods to find out which one is conflicting with yours, so I started with just JEI and Survivalist.

Using forge 13.20.0.**2252**

1. got a log
2. put it in the personal crafting grid
3. got the chopping block
4. placed it
5. put a log on it by right clicking the log onto it
6. got a wooden axe
7. click
8. click
9. click
10. click
11. log vanishes
12. not in inventory
13. not nearby
14. no planks either

https://www.youtube.com/watch?v=kKmcr4pvTmM

**Comment by mileswest07** [comment]
+1 here, issue is verified.
Tried also with no planks in inventory, just in case. No planks produced.
Tried also with a brand new chopping block. No planks produced.

**Comment by gigaherz** [comment]
I just released version 1.10.0, which includes a fix for this issue. It will be available at curseforge as soon as it's reviewed.
