### ISSUE TITLE
[1.10.2] Crash with Mekanism?

### ISSUE THREAD

**Issue by Kiyaku** [gigaherz/Survivalist#4]
Heya,

just tried to add the mod to my pack and i'm getting following crash on startup: http://pastebin.com/vgUw2MFi 

Would this be an issue on Mekanisms side or something else? 

Let me know if you need more info!

Thanks,
SC

**Comment by gigaherz** [comment]
Curious... Looks like an issue on my mod, but I will have to debug the issue. I'll get back to you later when I'm back from work and have had a proper look at it.

**Comment by gigaherz** [comment]
v1.5.3 is up here on github, curseforge downloads incoming.

**Comment by Kiyaku** [comment]
Awesome thanks a lot, works great!
