### ISSUE TITLE
Plant fibers BOP compatability

### ISSUE THREAD

**Issue by WolfieWaffle** [gigaherz/Survivalist#41]
I was wondering if BOP bushes drop plant fibers and if not would this be possible?

**Comment by gigaherz** [comment]
Not currently, the fibers are exclusively dropped from tall grass and ferns. Adding explicit compatibility should be possible, but I'm not a fan of having mod-specific things...

Do you have any idea if there's some existing mod that could add custom drops? Like some script for CraftTweaker or something?

**Comment by WolfieWaffle** [comment]
hmm, not that I am aware of. BOP seems to cause a lot of compatibility annoyances what with all the woods and bushes and everything, there really should be some sort of "wood block" object that automatically detects wood and make recipes and uses textures etc., not sure how possible that is but it would be cool if forge added it. For now I think I'm ok with it not dropping from BOP grasses, but ill look for a mod that could do that.

**Comment by gigaherz** [comment]
I have built and uploaded v2.1.5 (awaiting review), which includes BOP plant compatibility. Have fun!
