### ISSUE TITLE
Drying rack progress is reset on world exit

### ISSUE THREAD

**Issue by WolfieWaffle** [gigaherz/Survivalist#42]
If you are drying something and exit the world, when you go back in the progress will be reset.

**Comment by WolfieWaffle** [comment]
Actually it might just be visual... either way try it and see

**Comment by gigaherz** [comment]
I'll check.

**Comment by gigaherz** [comment]
I just released version 1.10.0, which includes a fix for this issue. It will be available at curseforge as soon as it's reviewed.
