### ISSUE TITLE
[1.11.2] Migmag Tech Pack crashed

### ISSUE THREAD

**Issue by Migmag789** [gigaherz/Survivalist#45]
Hello. I'm the creator of Migmag Tech Pack in Curse, and I'm developping a beta to the 1.3. But... Survivalist has crashed the game. Look the crash report please. Thank you :D
[crash-2017-05-18_22.00.05-client.txt](https://github.com/gigaherz/Survivalist/files/1012311/crash-2017-05-18_22.00.05-client.txt)

**Comment by gigaherz** [comment]
Hmm crap, I made a mistake in Packing Tape, that uses "survivalist" for an internal name, and it collides with the real Survivalist. I'll release a fix for Packing Tape asap.

**Comment by gigaherz** [comment]
I have uploaded v0.6.2 of Packing Tape to curseforge. It is in review as I write, but will be available soon. It should fix the problem.

**Comment by gigaherz** [comment]
If it still happens, feel free to reopen or comment.

**Comment by Migmag789** [comment]
Thank you :D
