### ISSUE TITLE
Config request

### ISSUE THREAD

**Issue by AshZification** [gigaherz/Survivalist#46]
Let me put this request here, instead of on Twitter! When you're able, could you please add allowing changing the amount of planks yielded based on the harvest level/axe material in the configs  :)

**Comment by Darkosto** [comment]
I would love this option, too. I've been working on another modpack using this feature and am limited a bit by the hardcoded amounts. Thank you :)

**Comment by gigaherz** [comment]
I wanted to work on extra features after the initial port to 1.12, but that port is going to take a LOT more effort than I thought, so I may revisit this before the port instead... :P

**Comment by gigaherz** [comment]
Survivalist 2.0 for 1.12.1 is very close to being released, and will have this feature. The configuration will look like this:

```
axemultipliers {
    D:AxeLevel1=5.0
    D:AxeLevel2=10.0
    D:AxeLevel3=15.0
    D:AxeLevel4=20.0
    D:AxeLevel5=25.0
}
```

Thanks for the suggestion!
