### ISSUE TITLE
[1.10.2] Cannot place log on Chopping Block. [Found Solution!]

### ISSUE THREAD

**Issue by LordDan1989** [gigaherz/Survivalist#47]
**Versions**
Minecraft: 1.10.2
Forge: 2185
Survivalist: 1.9.0

Logs cannot be placed on top of the chopping block. Instead they are placed in the new block space above it, similar to placing a full block on top of a half slab. This includes all logs; Vanilla and Modded.
There are no crashes. There are no errors/warns or anything in the console. The block is merely being treated as a basic half slab.

I've narrowed down the problem to a conflict with Better with Mods version: 0.14.23 (latest). This problem seems to have been persistent for sometime, being present as far back as 0.14.2 (December 2016)

Tests done on fresh install using only Forge, BwM and Survivalist.

---EDIT---
The following appears to be the same bug: #34 #26 

---FOUND SOLUTION---
In the betterwithmods.cfg turn off [false] the Hardcore Lumberjack setting. This has allowed me to place blocks back on the chopping block.

**Comment by LordDan1989** [comment]
@kreezxil Please see above for solution I found today and confirm this is the same for you on 1.11.2.

**Comment by Nhystel** [comment]
Ty <3
