### ISSUE TITLE
1.11.2-1.9.0 TorchFire when disabled still causes fires

### ISSUE THREAD

**Issue by kreezxil** [gigaherz/Survivalist#48]
I have discovered for the last few versions that survivalist appears to ignore the torchfire boolean setting. I have mine set to false and yet torches still cause fires.

```
torchfire {
    B:Enable=false
}
```

I have that setting on both client and dedicated server.

I have Minecolonies in my packs and people have only ever reported this when Minecolonies is installed, do you know if any compatibility issues?

**Comment by AshZification** [comment]
I have both 1.11.2 mods installed (survivalist 1.11.2-1.9.0 and mine colonies  1.11.2-0.8.1784), I have not had this issue.

**Comment by kreezxil** [comment]
You can close this, the problem was with itemphysic mod by creativemd, he
released a fix already.
