### ISSUE TITLE
Custom Chopping Block Tools Not Detecting/Working Correctly

### ISSUE THREAD

**Issue by Darkosto** [gigaherz/Survivalist#49]
Hello!

When working with the whitelist in the Survivalist config, certain items from mods do not work on the chopping block. During loading, the following errors are shown in the client console:

https://pastebin.com/gYTDKJSX

I have a suspicion that this is due to loading order, maybe moving detection to post-init instead of pre-init (parseChoppingAxes)?

MC: 1.11.2
Forge: 2311
Survivalist: 1.9.0

Thank you for looking into this, let me know if I can provide any more information. Hope you're having an absolutely fantastic evening. Take care! o/
Darkosto

**Comment by AshZification** [comment]
This guy seems to like to yell.  At about 5:30 or so is where he's testing it on stream, to make like a little easier for you to locate - https://www.twitch.tv/videos/148988368

**Comment by gigaherz** [comment]
I just released version 1.10.0, which includes the fix for this issue. It will be available at curseforge as soon as it's reviewed.

**Comment by Darkosto** [comment]
Heya @gigaherz ,

So I ran into one more issue related to this: When adding an axe that is detected by Survivalist, it won't be overwritten if I add the same tool to the config for a custom axe. For example, I have a mod adding a bone axe (which now works due to your change) but, I want to increase it's axe level. It seems like the config is overwritten by its hardcoded level, is it possible to make configs override?

Thank you! 
Darkosto

**Comment by Darkosto** [comment]
Actually, it looks like the issue may lay in Survivalist not taking meta data into account for the items on the config: When using it as a new item, the config allows the level to be affected but as soon as it takes damage it goes back it's hardcoded level. I assume wildcards cannot be used in the config, is there a way to allow for a damaged tools to be read from the config without listing out all of their meta-data values?

Thank you :)
Darkosto
