### ISSUE TITLE
Chopping Block Request

### ISSUE THREAD

**Issue by Darkosto** [gigaherz/Survivalist#5]
Hello!

Is it possible to allow the chopping block durability to be configurable? I love the mod and mechanics, but the chopping block seems to wear out so fast!

Thank you!
Darkosto

**Comment by gigaherz** [comment]
Sure. I'll add some config for that later after work. :)

**Comment by Darkosto** [comment]
Awesome! Thank you very much :)

**Comment by gigaherz** [comment]
v1.6.0 adds a config for this, among many other changes.
