### ISSUE TITLE
[1.10] Leather Works's logas support

### ISSUE THREAD

**Issue by wenlfs** [gigaherz/Survivalist#53]
Can you, please, support the debarked logs from Leather Works? They are only vanilla logs debarked, they craft vanilla planks.

Mod link: https://minecraft.curseforge.com/projects/leather-works?gameCategorySlug=mc-mods&projectID=269714

Thank you!

**Comment by gigaherz** [comment]
Hello, sorry that I haven't been paying attention to the issue tracker lately, life kept me busy. 

You can add chopping and drying recipes using CraftTweaker scripts, and you can also remove the normal recipes for those logs if you want. I hope you will understand that I'm not really interested in adding explicit mod integrations that can be easily fixed using CraftTweaker. :)
