### ISSUE TITLE
Tanned leather armor strange values

### ISSUE THREAD

**Issue by WolfieWaffle** [gigaherz/Survivalist#54]
Tanned leather leggings and boots seem to have double the armor value, 4 and 2 respectively. Making it 2 and 1 would make it fit better with leather armor, which the helmet and chest plate seem to be based on.

**Comment by gigaherz** [comment]
Will be fixed in v2.0 for 1.12(.1), thanks for reporting. Might backport later, but I'm busy with the 1.12 ports right now.
