### ISSUE TITLE
Survivalist creates a Commons File During Pack Load?

### ISSUE THREAD

**Issue by Darkosto** [gigaherz/Survivalist#55]
Can you provide some more information on the commons mod that is created during pack load in 1.12?

**Comment by gigaherz** [comment]
First, it's not downloading it, it's embedded into the jar using the jar-in-a-jar system that has existed for years (even before 1.7.10). Forge itself extracts those dependencies automatically on load. You may have seen it used for CodeChickenLib and a few others. Like Survivalist, they aren't downloading anything either.

As for the library itself, it's not a mod, just a few helper classes: https://github.com/gigaherz/Commons

There has been some effort recently to improve this system by eventually allowing forge to create a local repository of mods and libraries, from which packs can pick. It was thanks to that effort that I learned about the jar-in-a-jar feature, and decided to try it out.

However, you made me realize that using "Commons" as the name of the library can be quite confusing. I'll probably change the name of the jar file to something less confusing in a future release.

**Comment by jaredlll08** [comment]
I would suggest something like "gigaherz-commons", just so people know where to look.

**Comment by gigaherz** [comment]
![image](https://user-images.githubusercontent.com/685851/29032611-5792ce64-7b92-11e7-9eb0-1957702c12e8.png)

We had the same idea... ;P

**Comment by gigaherz** [comment]
I think I like "gigaherz.Commons" better though... so I'll go with that one instead.

**Comment by PaleoCrafter** [comment]
When the updated system is merged, you'll be able to specify a whole artifact, so confusions like this won't happen again ;)
