### ISSUE TITLE
Abyssalcraft - darklands wood can not be chopped

### ISSUE THREAD

**Issue by Seth0067** [gigaherz/Survivalist#57]
This is a bit odd since you CAN make a chopping block out of this wood, but I was unable to chop wood from the Darklands biome logs via the Abyssalcraft mod. The wood log is instead placed on top of the block (with that slab spaced gap)

Using latest versions of everything (except perhaps Forge)

**Comment by gigaherz** [comment]
You will need to add a recipe for it using CraftTweaker. Although I was able to make the chopping block recipe accept any log (this is no longer true in 1.12, due to some redesign), I can't just automatically register recipes for other mods. Adding chopping recipes is easy enough that it shouldn't be an issue for anyone making a modpack.

**Comment by Seth0067** [comment]
cool - i wasnt aware i could do chopping recipes. i'll see if i can figure it out.

**Comment by Seth0067** [comment]
Hi again!  Based on your responses in other issues i've tried
gigaherz.survivalist.Choppable.addRecipe(<abyssalcraft:dltlog>,<abyssalcraft:dltplank>,1);
and
mods.survivalist.Choppable.addRecipe(<abyssalcraft:dltlog>,<abyssalcraft:dltplank>,1);
and just
survivalist.Choppable.addRecipe(<abyssalcraft:dltlog>,<abyssalcraft:dltplank>,1);

with no luck. using /ct syntax it seems to have trouble finding "gigaherz" and "survivalist".  any suggestions?

**Comment by davqvist** [comment]
https://github.com/gigaherz/Survivalist/blob/master/src/main/java/gigaherz/survivalist/integration/MineTweakerPlugin.java

It seems that CraftTweaker Integratin is commented out at the moment. I wonder if you plan to readd that in the future?

**Comment by gigaherz** [comment]
Ouch! Yeah the 1.12 release has it disabled. I was going to re-enable it as soon as the 1.12 crafttweaker released, but I forgot.

I just released v2.1.1 which has the integration updated to 1.12 crafttweaker, along with a surprise feature.
