### ISSUE TITLE
Crash with JEI

### ISSUE THREAD

**Issue by Regulith** [gigaherz/Survivalist#6]
Loading into my world is crashing the game due to Just Enough Items being unable to start, but only due to an issue with another mod, which I believe to be Survivalist. The crash persists up until I disable Survivalist, so I can only assume that's where the problem is coming from. I attempted to roll back to Survivalist 1.6.1 because I thought it was a problem with the latest update, but that didn't help either.

Crash report: http://pastebin.com/m9TCzvJi
With only JEI and Survivalist enabled: http://pastebin.com/zxUKTYsw

**Comment by gigaherz** [comment]
Strange... can't be the version of JEI since I used 234 to build, which is the same you have there. Will investigate.

**Comment by Regulith** [comment]
It only appeared after several hours of playing on that world, if that's any help.

**Comment by gigaherz** [comment]
Wait! Did you disable the chopping block, or the drying rack? That would explain it.

**Comment by Regulith** [comment]
Yes, actually, I did! Since the chopping blocks weren't working for BoP logs in a previous version, I disabled them. I just re-enabled them and the world loaded up just fine. Thanks!

**Comment by gigaherz** [comment]
Yep, I'll be releasing a bugfix in a moment, regardless. ;P

**Comment by gigaherz** [comment]
Fix is up here on github, curseforge incoming.
