### ISSUE TITLE
Sawmill insta processes the first log

### ISSUE THREAD

**Issue by davqvist** [gigaherz/Survivalist#60]
Survivalist 2.0.0
Forge 2456
MC 1.12.1

If I place down the Sawmill and put any log and fuel in, the first log get insta processed, while others get processed normally. If I remove everything from the slots and put them back in, it doesn't happen again, so it only happens when you first place down the Sawmill.

**Comment by davqvist** [comment]
If you need more information for this, let me know. Would really include this block in my progression.

**Comment by gigaherz** [comment]
hmm... oops, I missed this ticket somehow.

**Comment by gigaherz** [comment]
v2.1.2 is up on curseforge, will be available as soon as it passes review.
