### ISSUE TITLE
Biome o Plenty

### ISSUE THREAD

**Issue by bob0bob** [gigaherz/Survivalist#61]
Is there any plans to make your mod work with Biomes O Plenty.   Biomes  define all the wood not the same as minecraft.  the logs, planks all have their own definition and ore dictionary also.
I see in the code from chopping block you pass in recipe for ore dictionary,  wonder if you plan on making it work with biomes o plenty.

**Comment by Dpuzak** [comment]
+1 for this. It would be great to have this feature. Appriciate the mod and all the free time that went into it very much. The mechanics it brings are great and I love them, but I also use Biomes o Plenty and in the end disabled Survivalist in my personal mod as there are new trees and plants and it was a pain searching only for the vanilla ones to have the basics working.

**Comment by gigaherz** [comment]
I have made Survivalist able to drop fibres from BOP plants. The existing system is already able to import the log->planks recipes, and the existing sticks recipes are already able to work with BOP leaves, saplings, and logs.

This leaves the chopping block. Originally I had a single chopping block that always looked like oak, and any log item would have worked for it, but now I have specific variants for all vanilla logs.

Technically, I could spend the time to create variants for mod blocks, and "activate" them when the mod is detected, but I really don't want to go that route. Between Forestrey and BOP, there's 40 extra log variants I'd have to create chopblocks for -- and that's just the first two "tree-adding" mods that come to mind. I'll continue thinking of a solution, but chances are it won't be in the next release yet -- modpacks can add custom recipes for non-vanilla logs, that output one of the vanilla-styled chopblocks.

**Comment by Snownee** [comment]
> I have made Survivalist able to drop fibres from BOP plants.

Is that available in the latest version on CurseForge? As for my test it doesn't work.

**Comment by gigaherz** [comment]
No, I never got around to releasing a new update, yet... I have had too many things going on in my head lately, and I couldn't feel motivated about modding.

**Comment by gigaherz** [comment]
I have built and uploaded v2.1.5 (awaiting review), which includes BOP plants compatibility. Have fun!
