### ISSUE TITLE
[Suggestion] JEI and CraftTweaker integration for Sawmill

### ISSUE THREAD

**Issue by davqvist** [gigaherz/Survivalist#63]
Pretty much the title. Would enable me to support other mods logs and also add other recipes.
MC 1.12

**Comment by gigaherz** [comment]
The sawmill takes the same recipes as the chopping block, so if you add them as chopping block recipes, they will work on the sawmill. You are right though, that I should mark the sawmill in JEI, as a machine that can process chopping recipes!

**Comment by gigaherz** [comment]
v2.1.3 is up on curseforge, and will be available as soon as it's reviewed. It will now properly show the sawmill as a chopping machine.

**Comment by davqvist** [comment]
Thanks very much.
