### ISSUE TITLE
Crash with Vex

### ISSUE THREAD

**Issue by davqvist** [gigaherz/Survivalist#64]
Survivalist 2.1.3
Forge 2512
MC 1.12.2

I spawned in a Vex in a test world, a few seconds later I crashed.

https://pastebin.com/uesBTXfD

**Comment by gigaherz** [comment]
I seems that the "item bracking tracker" hack is doing something wrong. I'll take a look when I get home.

**Comment by gigaherz** [comment]
I have built and uploaded v2.1.5 (awaiting review), which I hope shouldn't have this issue. Feel free to comment here if it still happens.
