### ISSUE TITLE
CraftTweaker2 integration broken in 1.12.2

### ISSUE THREAD

**Issue by TensorTime** [gigaherz/Survivalist#65]
Versions using: 

Survivalist-1.12.2-2.1.3.jar
forge 14.23.0.2512
CraftTweaker2-1.12-4.0.8

Expected Result:
I had existing scripts for adding forestry logs to Chopping blocks here:
https://gist.github.com/TensorTime/41234de73f96ffba5a2048a18ca2227e

With the latest updated to 2.1.3 I noticed none of those recipes were working anymore and reverting to the previous Survivalist version 2.1.2 they are fixed.  Not sure if maybe the function in Zen changed but I'm also not seeing any errors pop out from CraftTweaker when it loads the script.

I've tried reverting CraftTweaker (since it also had a recent update), along with Forestry for the same reason.  No matter what the only update which breaks the recipes is upgrading Survivalist to 2.1.3.  When it's on 2.1.2 everything works regardless if they are on their latest versions or older ones.

**Comment by trienow** [comment]
The weird thing is, your script works for me.
I've got Survivalist 2.1.3 and CraftTweaker2 4.0.8 installed.
However I'm on forge 14.23.0.2517 and my Forestry version is 5.6.0.201.

**Comment by Ganjalf-Amsterdoom** [comment]
I've got the same problem, forge for 1.12.2  14.23.0.2537 99.

Here a sample from my script:

gigaherz.survivalist.Choppable.addRecipe(<minecraft:log>,<minecraft:planks>, 1.0, 1.0);

**Comment by trienow** [comment]
1. Don't forget the brackets, when using Item IDs
2. Use `/ct syntax` to check your scripts for errors

**Comment by Ganjalf-Amsterdoom** [comment]
Oh my bad, i'm going to try it. Thank you for your time.

**Comment by Ganjalf-Amsterdoom** [comment]
Also with brackets it still gives errors, mc 1.12.2, forge 14.23.1.2555,

Here the script:  https://pastebin.com/tyCV70C2

And here the CT log: https://pastebin.com/btyYKUvC

What did i do wrong? And again thank you for your time.

**Comment by gigaherz** [comment]
Line 18 in the script is wrong. Lines 92+ seem like those items don't exist, or CT has issues with the dots in the item names. Either way, given that lines 1 to 91 (with the exception of line 18) DO work, I would say that CT integration is working as intended, and the issues are unrelated to Survivalist.

**Comment by Ganjalf-Amsterdoom** [comment]
Ohhh, i see, again my bad. Thank you so much.
