### ISSUE TITLE
Missing Saplings to Sticks

### ISSUE THREAD

**Issue by royalcw** [gigaherz/Survivalist#66]
Can't find the Saplings to Sticks option in the config file.  Currently, to acquire sticks requires saplings or the leaves as you have created, thus the need to enable this feature.

**Comment by gigaherz** [comment]
It is not an issue of the configuration. The recipe DOES exist, and is always enabled, but for some reason it does not match the oredict name "treeSapling" with the item. I will try to fix it as soon as I get back from work.

**Comment by gigaherz** [comment]
I tracked down the issue to a flaw in the vanilla recipe removal (it would remove my own recipes also!). I didn't have time to do a test session yesterday, so I will try to get it released later today.

**Comment by gigaherz** [comment]
It should be fixed now, v2.1.4 is out on curseforge.
