### ISSUE TITLE
chopping block not working

### ISSUE THREAD

**Issue by Mythgarian** [gigaherz/Survivalist#67]
So not sure if its just the chopping block not working or what but when you place a wood block on it and try to break the block to get planks you can only target the chopping block and it breaks thought possibly might be the type of axe but no axe works so no progression nice idea but useless unless you can make planks

**Comment by gigaherz** [comment]
You have to click multiple times, not hold the break button. I haven't figured out how to allow holding, yet.

**Comment by Mythgarian** [comment]
LOL ok worked fine that way couldn't for the life of me figure it that out, thank you

**Comment by gigaherz** [comment]
No problem! It is something I do want to improve someday. :)
