### ISSUE TITLE
Broken Gravel Craft in Minecraft 1.12

### ISSUE THREAD

**Issue by AllInMods** [gigaherz/Survivalist#69]
The basic craft of gravel from Survivalist in Minecraft 1.12.* use : survivalist:rock:32768 but you've changed the id for : surivalist:rock.

**Comment by gigaherz** [comment]
I have not changed the id, but it is true that the crafting recipe is broken. Fixing.

**Comment by AllInMods** [comment]
Thanks !

**Comment by gigaherz** [comment]
I have built and uploaded v2.1.5 (awaiting review), which I hope shouldn't have this issue. Feel free to comment here if it still happens.
