### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Drakoflame** [gigaherz/Survivalist#7]
http://pastebin.com/dm7zs6Qe Not sure whats happening, I have no knowledge of code, but I do know how to read:
"	at net.minecraftforge.oredict.OreDictionary.getOreIDs(OreDictionary.java:432)
	at gigaherz.survivalist.Survivalist.hasOreName(Survivalist.java:263)"

I think it has soething to do with Survivalist and ore dictionary stuff... so... if you could give it me a look

**Comment by gigaherz** [comment]
One of the mods is creating, probably due to a bug, an ItemStack with a null item inside. This is bad practice. I will protect against it, but I can't tell which mod is the real culprit, due to the ItemStack having no item to identify.

**Comment by gigaherz** [comment]
v1.6.4 is up here on github. curseforge incoming.
