### ISSUE TITLE
Question about models

### ISSUE THREAD

**Issue by WolfieWaffle** [gigaherz/Survivalist#73]
I saw you said you would add more ore support if someone made a texture, I am attempting to do this but also do the code side on my fork to get coding practice and save you the effort (don't worry I will preserve style and all that) but I don't understand how you are registering the models. There is no .json (in fact eclipse keeps giving me a null exception on them, don't understand that) and the registerAllModelsExplicitly() method looks like it uses some kind of weird internal forge thing, I don't see any reference to the actual mod.

If possible, could you explain how your model loading system works? How would I make sure that a new ore rock has a model? As is it has none, and I don't see what I'm missing.

**Comment by gigaherz** [comment]
ItemStateMapper is a thing I wrote, it's in this other repository: https://github.com/gigaherz/Commons/blob/master/src/main/java/gigaherz/common/state/client/ItemStateMapper.java

It generates model names based on the declared state properties, so you will have to add the new ore to `OreMaterials`, and add the variant to all the related blockstates json files (nugget and rock_ore).
