### ISSUE TITLE
[1.12.2-2.1.4] No tooltips in drying rack

### ISSUE THREAD

**Issue by xt9** [gigaherz/Survivalist#76]
As title says, Hovered items render correctly before 1.12 in any Gui but after, you need to call it explicitly. Personally (In own projects) I solved it by calling renderHoveredTooltip in drawScreen.

Image of current behaviour:
https://i.imgur.com/C2NVGTd.png

```
    /* Needed on 1.12 to render tooltips */
    @Override
    public void drawScreen(int mouseX, int mouseY, float partialTicks) {
        drawDefaultBackground();
        super.drawScreen(mouseX, mouseY, partialTicks);
        renderHoveredToolTip(mouseX, mouseY);
    }
```

**Comment by gigaherz** [comment]
Yes I had to update every other machine too, I guess I missed one...

**Comment by gigaherz** [comment]
I have built and uploaded v2.1.5 (awaiting review), which fixes this issue.
