### ISSUE TITLE
Desync on Chopping Block

### ISSUE THREAD

**Issue by davqvist** [gigaherz/Survivalist#77]
Survivalist 2.1.4
Forge 2688

On servers, but also ocassionally in Singleplayer, the Chopping Block has a desync when the log is broken. The log sits still there visually on the Chopping Block even though it is already broken. Placing another log first places it on top in world until the client realises that there is actually room on the Chopping Block and it places the log on the Chopping Block

**Comment by gigaherz** [comment]
Hmmm, strange, I'll look into it. I'm probably missing some sync request somewhere.

**Comment by Arkimu** [comment]
Any news?

**Comment by gigaherz** [comment]
I have fixed the desync issue, next release (soon), will contain this fix.

**Comment by gigaherz** [comment]
I have built and uploaded v2.1.5 (awaiting review). Feel free to comment here if it still happens.
