### ISSUE TITLE
Dark Oak chopping block becomes Acacia as it wears out

### ISSUE THREAD

**Issue by davqvist** [gigaherz/Survivalist#79]
Survivalist 2.1.4
Forge 2688

See https://github.com/davqvist/Exoria/issues/224
I could replicate it myself

**Comment by hron84** [comment]
Same with Spruce, becomes Oak.

**Comment by gigaherz** [comment]
ouch! Yes I see why.
```worldIn.setBlockState(pos, getDefaultState().withProperty(DAMAGE, damage + 1));``` Yep it's going to default to Oak always ¬¬
Fixed locally. Will take this chance to look at a few more reports and i'll push an update.

**Comment by gigaherz** [comment]
I have built and uploaded v2.1.5 (awaiting review), which fixes this issue. Feel free to comment here if it still happens.
