### ISSUE TITLE
[1.12.2] Survivalist messing with JEI's recipes

### ISSUE THREAD

**Issue by Stantrien** [gigaherz/Survivalist#80]
For some reason Survivalist is messing up JEI in the latest versions, making few if any recipes show up, and the problem goes away if I remove survivalist.  I'm using survivalist 2.1.4 and JEI 4.9.2.196

**Comment by gigaherz** [comment]
Hmmm I compiled 2.1.4 with an older JEI, maybe it's not properly compatible, I'll check...

**Comment by gigaherz** [comment]
I have built and uploaded v2.1.5 (awaiting review), which I hope shouldn't have this issue. Feel free to comment here if it still happens.
