### ISSUE TITLE
[1.12] java.lang.NullPointerException with First Aid

### ISSUE THREAD

**Issue by MasterEnderman** [gigaherz/Survivalist#81]
Survivalist: 2.1.4
Forge: 14.23.4.2707
First Aid: 1.5.4
Crash Report: https://paste.dimdev.org/emogilawib.mccrash

If you get a poison effect the game crashes.

**Comment by gigaherz** [comment]
I put a null-check in that method, but since there are coremods involved, I don't know that it will fully prevent the crash... I coudln't reproduce it locally.

**Comment by gigaherz** [comment]
I have built and uploaded v2.1.5 (awaiting review), which I hope shouldn't have this issue. Feel free to comment here if it still happens.
