### ISSUE TITLE
[1.12.2 / 2.1.4]Unable to make gravel

### ISSUE THREAD

**Issue by TrialDragon** [gigaherz/Survivalist#82]
When I try to make gravel with 4 rocks nothing shows in the output.
![2018-06-17_10 50 12](https://user-images.githubusercontent.com/31419708/41510659-8c9d26a4-721d-11e8-830d-b86624d06037.png)
![2018-06-17_10 56 10](https://user-images.githubusercontent.com/31419708/41510661-91a0973a-721d-11e8-95e1-dcb9cbd5810b.png)

**Comment by gigaherz** [comment]
I have tried to reproduce, but it works just fine for me :/
What other mods do you have installed? Are there errors in the debug logs? (You can enable the log window in the launcher settings, if you use the modern vanilla launcher)

**Comment by gigaherz** [comment]
I have built and uploaded v2.1.5 (awaiting review), which I hope shouldn't have this issue. Feel free to comment here if it still happens.

**Comment by TrialDragon** [comment]
Yep, that fixed it.
