### ISSUE TITLE
gigaherz.commons on the latest version installs in a folder stopping the mod working in older forge 

### ISSUE THREAD

**Issue by kiwifrogg** [gigaherz/Survivalist#84]
Because of an issue with another mod we are stuck with 2611 forge, however, we updated rockhounding, that uses guidebook, the new version of guild book has moved gigaherz.commons to a memory_repo folder. forge 2611 can not see gigaherz.commons in that folder and crashes the game if you move gigaherz.commons into the mods folder it works fine.  I've not tried but I have a feeling that curse will reject gigaherz.commons if added to the pack direct. 

Is there an easy fix, like add gigaherz.commons to curse, or can u have gbook put gigaherz.commons in both spots?

**Comment by kiwifrogg** [comment]
I'd not expect globby to have moved it into a folder, It looks more like a forge thing, it ends up in mods\memory_repo\gigaherz\commons\gigaherz.commons-1.12.1\0.6.4

Thanks for the info, guess we'll have to update forge and see if we can get an update to the other mod. 

Thanks again :)

**Comment by gigaherz** [comment]
Yes that's what newer forge does. If your forge is new enough to have the new dependency extraction, then the library should work find from that folder, unless the version you used had some bug.

**Comment by gigaherz** [comment]
I removed the commons lib in v2.1.6, so this issue doesn't apply anymore.
