### ISSUE TITLE
The Hardened Glass is Missing

### ISSUE THREAD

**Issue by JokeReindeer** [gigaherz/Survivalist#87]
When I open back my world i tried to craft a reinforced capacitor; so, when I press "u" my game crashes, I started my game again, I searched for hardened and then theres a big chuck of missing items.
Please help me.

**Comment by gigaherz** [comment]
Do you have any reason to believe that this issue was caused by
Survivalist? Do you have a crash log?

**Comment by gigaherz** [comment]
I am assuming this is not my mod's fault.

**Comment by JokeReindeer** [comment]
Yeah It wasn't, I think that my instance was just corrupted so I loaded up
a new one.
Thanks for the reply
