### ISSUE TITLE
Allow customizing the drop multipler when using the chopping block with bare hands

### ISSUE THREAD

**Issue by CrankySupertoon01** [gigaherz/Survivalist#88]
Customize it in the configs. Or tell me if its possible via crafttweaker

**Comment by CrankySupertoon01** [comment]
https://github.com/CrankySupertoon01/Rebirth-3/issues/7

**Comment by gigaherz** [comment]
v2.1.6 is up on curseforge, and it comes with a config option for chopping with empty hand.
