### ISSUE TITLE
Mod compatibility

### ISSUE THREAD

**Issue by Silvrus** [gigaherz/Survivalist#9]
Hey dude, not sure if you can do anything about this, but Better With Mods adds an in world saw that cuts logs using mechanical power into planks, but Survivalist is grabbing the drop and turning the 6 planks into 3 chopping blocks. If you've time, can you look and let me know if it's something that can be fixed?

**Comment by gigaherz** [comment]
o_O I'm most definitely not "grabbing drops" for woods, in my mod, that code only cares about rocks and ores. I wonder if they are looking for recipes that take logs as input, but they don't check if the output is actually planks? That wouldn't be my fault, though...

**Comment by Silvrus** [comment]
It's possible. On it's own you get 6 planks, 2 bark and 2 sawdust, but combined you get 3 chopping blocks, lol. I'll open an issue with them and check it out. Thanks!

**Comment by Silvrus** [comment]
Figured it out, looks like you're right. Turning off the setting in Survivalist to remove planks recipes makes the saw work properly. It may be easier for me to CraftTweak the crafting table plank recipe out.

**Comment by gigaherz** [comment]
That's why the settings are there. Although I don't have any way to add planks recipes to my machine, but NOT remove them from the normal crafting... I should change that. ;P

**Comment by Silvrus** [comment]
Thanks so much for being patient with me, you've been a great help with getting all these things ironed. The ore and wood issues have been fixed by their respective devs, I wouldn't have know where to go had you not pointed me in the right direction. Keep up the awesome work, looking forward to more from you!
