### ISSUE TITLE
[1.15.2 Survivalist] Iron Ore is not dropping iron ore rocks

### ISSUE THREAD

**Issue by dreckz** [gigaherz/Survivalist#95]
Whenever Iron Ore is mined, it does not drop the iron ore rocks.

**Comment by gigaherz** [comment]
I'll look into it.

**Comment by gigaherz** [comment]
Oops! I had the tag file as "ore/iron", instead of "ores/iron". Fixed the tags. Will push update as soon as I do some testing.

**Comment by gigaherz** [comment]
Should work as of v3.0.1, which is being reviewed on curseforge and will be available shortly.
