### ISSUE TITLE
Add Drying Rack, Sawmill and Chopping Block recipes through datapacks

### ISSUE THREAD

**Issue by slard3** [gigaherz/Survivalist#98]
Could it be possible for the mod to accept new recipes through datapacks?
Thanks for reading and hope you recover soon! :)

**Comment by gigaherz** [comment]
It **is** possible!
Both Drying and Chopping/Sawmill recipes use the standard recipe system. :)
note that currently Chopping and Sawmill share a recipe type, so it's not possible to make the two blocks process things differently.
See the chopping and drying folders [here](https://github.com/gigaherz/Survivalist/tree/master/src/main/resources/data/survivalist/recipes) for examples.

**Comment by slard3** [comment]
Hmm, that's weird. I've been trying to do a datapack with one of your recipes as a model, yet it hasn't worked.
I'm supposed to make it like this?
`{
  "type": "survivalist:chopping",
  "ingredient": {
    "tag": "biomesoplenty:palm_log"
  },
  "result": "biomesoplenty:palm_planks"
}`

**Comment by gigaherz** [comment]
is "biomesoplenty:palm_log" actually a tag? you probably want "item" instead.
```json
{
  "type": "survivalist:chopping",
  "ingredient": {
   "item": "biomesoplenty:palm_log"
  },
  "result": "biomesoplenty:palm_planks" 
}
```

**Comment by slard3** [comment]
That's so dumb of me.
Since all of the recipes have tag in it I didn't thought about changing it. Thanks for the replies and the help! It works now so I'll close this now.
